# Generated by Django 3.0.5 on 2020-04-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0002_auto_20200429_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
